### ISSUE TITLE
똑같은 클래스파일이 두개의 패키지 내에 존재함

### ISSUE THREAD

**Issue by JeongMinCha** [round-up/roundup_android#17]
add_group이랑 navigation에 AddGroupActivity가 똑같이 들어 있음.
완전히 같은 파일인지는 확인안해봄...

**Comment by kyeongwan** [comment]
확인하고 고치겠음.

**Comment by kyeongwan** [comment]
AddGroup 클래스 두개인데 사용은 add_group 패키지로 사용하고, 있어야 할 곳은 navigation 인 것 같음.
확인하고 편의에 맞게 수정하길 바람..

**Comment by JeongMinCha** [comment]
@kyeongwan ㅋㅋㅋ 똑같은 말 쓰고 있네

**Comment by JeongMinCha** [comment]
지금 add group activity 디자인 작업하면서 수정할 거
