### ISSUE TITLE
ClubActivity가 NavigationDrawerActivity를 상속받도록 고쳐야 함.

### ISSUE THREAD

**Issue by JeongMinCha** [round-up/roundup_android#18]
NavigationDrawerActivity에서 네비게이션드로워에 대한 처리를 하고 있음 (아이템을 탭하면 그 액티비티로 이동하는 등...) 그래서 네비게이션드로워가 등장하는 모든 액티비티는 가능하면 NavigationDrawerActivity를 상속하는 형태로 구현이 되어야 함. 

그리고 상속받은 클래스는 onCreate에서 makeNavigationDrawer를 호출해야 함.
이 메서드 코드 보고 이미 있는 코드는 중복안되게 잘 고쳐서 쓸 것. 
(툴바나 드로워같은게 두 개 있으면 충돌되는 걸로 암)

**Comment by kyeongwan** [comment]
Club 에서 collapsingToolbar 을 사용하기 때문에 안되네요..

**Comment by JeongMinCha** [comment]
@kyeongwan 넵! 그러면 NavigationDrawerActivity에서 따로 부를 수 있게 메서드를 새로 파서 만들어놓을게용
