### ISSUE TITLE
내부 DB를 realm을 쓸까 싶음.

### ISSUE THREAD

**Issue by JeongMinCha** [round-up/roundup_android#19]
지금 DynamicNavigation 브런치를 작업중인데, 이 브런치는 네비게이션 드로워에 있는 정보가 사용자의 내용에 맞게 동적으로 변화하도록 만들 브런치임. 예를 들어서 네비게이션 윗부분에 있는 배경사진이라던지, following 아래에 있을 그룹들의 목록이라던지 등을 내부 DB에서 가져오는 작업도 해야 할듯.

어차피 내부 DB를 짜긴 해야 하니깐 그냥 realm 구축하는 것을 이 브런치 내에서 처리할 예정.

**Comment by kyeongwan** [comment]
낼름 알겠습니다.
