### ISSUE TITLE
NavigationView에서 subMenu에는 아이콘 못넣는다고 함...

### ISSUE THREAD

**Issue by JeongMinCha** [round-up/roundup_android#20]
http://stackoverflow.com/a/12634394/3241257
subMenu자체가 icon을 지원하지 않는다고 함... ㅠㅠㅠ

부들부들... 디자인 가이드처럼 완벽하게 못 따라 할듯...
실은 방법은 있긴 한데... 네비게이션 뷰를 아예 예전에 하던 방식대로 리스트뷰로 뜯어고치는 방법....이 있긴 한데
지금 굳이 그런 선택은 안하는게 맞겠지.

**Comment by kyeongwan** [comment]
넵 그냥 그대로 진행합시다.
